---
area/ansible:
- changed-files:
  - any-glob-to-any-file: "ansible/**/*"
area/github:
- changed-files:
  - any-glob-to-any-file: ".github/**/*"
area/cluster:
- changed-files:
  - any-glob-to-any-file: "cluster/**/*"
area/hack:
- changed-files:
  - any-glob-to-any-file: "hack/**/*"
area/terraform:
- changed-files:
  - any-glob-to-any-file: "terraform/**/*"
