hajimari:
  namespaceSelector:
    matchNames:
      - downloads
      - media
  customApps:
    - group: media
      apps:
        - name: Test
          url: https://example.com
          icon: test-tube
        - name: Example
          url: https://example.org
          icon: test-tube
  globalBookmarks:
    - group: Communicate
      bookmarks:
        - name: Discord
          url: "https://discord.com"
        - name: Gmail
          url: "http://gmail.com"
        - name: Slack
          url: "https://slack.com/signin"
    - group: Cloud
      bookmarks:
        - name: Box
          url: "https://box.com"
        - name: Dropbox
          url: "https://dropbox.com"
        - name: Drive
          url: "https://drive.google.com"
ingress:
  main:
    enabled: true
    hosts:
      - host: hajimari.domain.tld
        paths:
          - path: /
            pathType: Prefix
persistence:
  data:
    enabled: true
